# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JenkensDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JenkensDemoApp

end

target 'JenkinsDemoApp_branch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JenkinsDemoApp_branch

end
